#!/usr/bin/env bash
# script to install and configure HAproxy on load balancer server

apt-get update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y install haproxy
